version: "3.7"
services:
  redis:
    build:
      context: infra/redis
    image: "safetynet-redis:5.0.7"
    networks:
      - safetynet
    # Increases the size of the backlog for maximum outstanding connections
    sysctls:
      - net.core.somaxconn=1024
  app:
    build:
      context: app
    image: "safetynet-app:1.0.0"
    environment:
      - FLASK_APP=/safetynet/app
      - FLASK_ENV=development
    # Doesn't wait for Redis to be fully configured before starting the app
    depends_on:
      - redis
    networks:
      - safetynet
    ports:
      - "5000:5000"
networks:
  safetynet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/28
